import sys
import os
import torch
import numpy as np
import time
import argparse

# Add project root to sys.path
project_root = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
if project_root not in sys.path:
    sys.path.append(project_root)

from src.board import GoBoard, BLACK, WHITE, SIZE, EMPTY
from src_large.model import TinyGoNet
from win_rate.src_small.model import ValueNetSmall
from src_mcts.mcts import MCTS
from src_large.inference import predict_move as predict_move_large

def print_board(board, last_move=None):
    print("   " + " ".join([f"{i:2}" for i in range(SIZE)]))
    for r in range(SIZE):
        row_str = f"{r:2} "
        for c in range(SIZE):
            color = board.board[r, c]
            char = "."
            if color == BLACK: char = "X"
            elif color == WHITE: char = "O"
            
            if last_move == (r, c):
                char = f"({char})"
            else:
                char = f" {char} "
                
            row_str += char
        print(row_str)
    print()

def main():
    parser = argparse.ArgumentParser(description='MCTS (Black) vs PolicyNet (White) CLI Battle')
    parser.add_argument('--sims', type=int, default=100, help='MCTS Simulations per move')
    parser.add_argument('--max_moves', type=int, default=200, help='Max moves before draw')
    parser.add_argument('--device', type=str, default='auto', help='Device to use')
    args = parser.parse_args()

    # Device
    if args.device == 'auto':
        device = 'cuda' if torch.cuda.is_available() else 'cpu'
    else:
        device = args.device
        
    print(f"Using device: {device}")
    
    # Load Models
    print("Loading models...")
    policy_path = os.path.join(project_root, 'best_model_large.pth')
    value_path = os.path.join(project_root, 'win_rate', 'src_small', 'best_model.pth')
    
    if not os.path.exists(policy_path) or not os.path.exists(value_path):
        print("Models not found! Please check paths.")
        return

    # 1. MCTS Policy
    mcts_policy = TinyGoNet(num_blocks=10, channels=128).to(device)
    mcts_policy.load_state_dict(torch.load(policy_path, map_location=device)['model_state_dict'])
    mcts_policy.eval()
    
    # 2. MCTS Value
    mcts_value = ValueNetSmall(num_blocks=6, channels=64, input_planes=2).to(device)
    mcts_value.load_state_dict(torch.load(value_path, map_location=device)['model_state_dict'])
    mcts_value.eval()
    
    # 3. Pure Policy (Separate instance)
    pure_policy = TinyGoNet(num_blocks=10, channels=128).to(device)
    pure_policy.load_state_dict(torch.load(policy_path, map_location=device)['model_state_dict'])
    pure_policy.eval()
    
    mcts = MCTS(mcts_policy, mcts_value, device=device, num_simulations=args.sims)
    
    # Game Loop
    board = GoBoard()
    passes = 0
    move_count = 0
    
    print("\n=== Battle Start: MCTS (X) vs PolicyNet (O) ===\n")
    
    while move_count < args.max_moves and passes < 2:
        current_color = board.next_player
        player_name = "MCTS (Black)" if current_color == BLACK else "PolicyNet (White)"
        
        start_time = time.time()
        move = None
        win_rate = 0.5
        
        if current_color == BLACK:
            # MCTS
            sys.stdout.write(f"Move {move_count+1}: {player_name} thinking... ")
            sys.stdout.flush()
            
            actions, probs = mcts.run(board, BLACK, temperature=0.5)
            best_idx = np.argmax(probs)
            move = actions[best_idx]
            
            # Value for Black
            win_rate = mcts._get_value(board) 
            
        else:
            # Pure Policy
            sys.stdout.write(f"Move {move_count+1}: {player_name} thinking... ")
            sys.stdout.flush()
            
            moves = predict_move_large(pure_policy, board, WHITE, device)
            if moves:
                move = moves[0][0]
                
            # Evaluate using MCTS Value Net for consistency
            wr_white = mcts._get_value(board) # Returns prob for Next Player (White)
            win_rate = 1.0 - wr_white # Convert to Black WR
            
        elapsed = time.time() - start_time
        
        # Output result
        if move is None:
            passes += 1
            print(f"PASS (WR: {win_rate:.1%}, {elapsed:.2f}s)")
        else:
            passes = 0
            r, c = move
            print(f"plays ({r}, {c}) (Black WR: {win_rate:.1%}, {elapsed:.2f}s)")
            
            if board.play(r, c, current_color) == -1:
                print(f"FATAL: Invalid move generated by {player_name}!")
                break
                
        # print_board(board, move) # Optional: uncomment to see board every move
        move_count += 1
        
    print("\n=== Game Over ===")
    print_board(board)
    
    # Calculate Score (Chinese Rules / Area Scoring - Simplified)
    # Just counting stones + surrounded empty points
    # This is a complex DFS, for now let's just count stones on board
    black_stones = np.sum(board.board == BLACK)
    white_stones = np.sum(board.board == WHITE)
    print(f"Stones on Board -> Black: {black_stones}, White: {white_stones}")
    
    # Final Win Rate check
    final_wr = mcts._get_value(board)
    if board.next_player == WHITE: # If next is White, value is for White
        final_wr = 1.0 - final_wr # Black WR
        
    print(f"Final Estimated Black Win Rate: {final_wr:.1%}")
    
    if passes >= 2:
        print("Result: Ended by double pass.")
    else:
        print("Result: Reached move limit.")

if __name__ == "__main__":
    main()
